sed -i 's/三星/samsung/g' ../data/app_events_full_basic.csv
sed -i 's/天语/Ktouch/g' ../data/app_events_full_basic.csv
sed -i 's/海信/hisense/g' ../data/app_events_full_basic.csv
sed -i 's/联想/lenovo/g' ../data/app_events_full_basic.csv
sed -i 's/欧比/obi/g' ../data/app_events_full_basic.csv
sed -i 's/爱派尔/ipair/g' ../data/app_events_full_basic.csv
sed -i 's/努比亚/nubia/g' ../data/app_events_full_basic.csv
sed -i 's/优米/youmi/g' ../data/app_events_full_basic.csv
sed -i 's/朵唯/dowe/g' ../data/app_events_full_basic.csv
sed -i 's/黑米/heymi/g' ../data/app_events_full_basic.csv
sed -i 's/锤子/hammer/g' ../data/app_events_full_basic.csv
sed -i 's/酷比魔方/koobee/g' ../data/app_events_full_basic.csv
sed -i 's/美图/meitu/g' ../data/app_events_full_basic.csv
sed -i 's/尼比鲁/nibilu/g' ../data/app_events_full_basic.csv
sed -i 's/一加/oneplus/g' ../data/app_events_full_basic.csv
sed -i 's/优购/yougo/g' ../data/app_events_full_basic.csv
sed -i 's/诺基亚/nokia/g' ../data/app_events_full_basic.csv
sed -i 's/糖葫芦/candy/g' ../data/app_events_full_basic.csv
sed -i 's/中国移动/ccmc/g' ../data/app_events_full_basic.csv
sed -i 's/语信/yuxin/g' ../data/app_events_full_basic.csv
sed -i 's/基伍/kiwu/g' ../data/app_events_full_basic.csv
sed -i 's/青橙/greeno/g' ../data/app_events_full_basic.csv
sed -i 's/华硕/asus/g' ../data/app_events_full_basic.csv
sed -i 's/夏新/panosonic/g' ../data/app_events_full_basic.csv
sed -i 's/维图/weitu/g' ../data/app_events_full_basic.csv
sed -i 's/艾优尼/aiyouni/g' ../data/app_events_full_basic.csv
sed -i 's/摩托罗拉/moto/g' ../data/app_events_full_basic.csv
sed -i 's/乡米/xiangmi/g' ../data/app_events_full_basic.csv
sed -i 's/米奇/micky/g' ../data/app_events_full_basic.csv
sed -i 's/大可乐/bigcola/g' ../data/app_events_full_basic.csv
sed -i 's/沃普丰/wpf/g' ../data/app_events_full_basic.csv
sed -i 's/神舟/hasse/g' ../data/app_events_full_basic.csv
sed -i 's/摩乐/mole/g' ../data/app_events_full_basic.csv
sed -i 's/飞秒/fs/g' ../data/app_events_full_basic.csv
sed -i 's/米歌/mige/g' ../data/app_events_full_basic.csv
sed -i 's/富可视/fks/g' ../data/app_events_full_basic.csv
sed -i 's/德赛/desci/g' ../data/app_events_full_basic.csv
sed -i 's/梦米/mengmi/g' ../data/app_events_full_basic.csv
sed -i 's/乐视/lshi/g' ../data/app_events_full_basic.csv
sed -i 's/小杨树/smallt/g' ../data/app_events_full_basic.csv
sed -i 's/纽曼/newman/g' ../data/app_events_full_basic.csv
sed -i 's/邦华/banghua/g' ../data/app_events_full_basic.csv
sed -i 's/E派/epai/g' ../data/app_events_full_basic.csv
sed -i 's/易派/epai/g' ../data/app_events_full_basic.csv
sed -i 's/普耐尔/pner/g' ../data/app_events_full_basic.csv
sed -i 's/欧新/ouxin/g' ../data/app_events_full_basic.csv
sed -i 's/西米/ximi/g' ../data/app_events_full_basic.csv
sed -i 's/海尔/haier/g' ../data/app_events_full_basic.csv
sed -i 's/波导/bodao/g' ../data/app_events_full_basic.csv
sed -i 's/糯米/nuomi/g' ../data/app_events_full_basic.csv
sed -i 's/唯米/weimi/g' ../data/app_events_full_basic.csv
sed -i 's/酷珀/kupo/g' ../data/app_events_full_basic.csv
sed -i 's/谷歌/google/g' ../data/app_events_full_basic.csv
sed -i 's/昂达/ada/g' ../data/app_events_full_basic.csv
sed -i 's/聆韵/lingyun
