sed -i 's/三星/samsung/g' phone_brand_device_model_translated.csv
sed -i 's/天语/Ktouch/g' phone_brand_device_model_translated.csv
sed -i 's/海信/hisense/g' phone_brand_device_model_translated.csv
sed -i 's/联想/lenovo/g' phone_brand_device_model_translated.csv
sed -i 's/欧比/obi/g' phone_brand_device_model_translated.csv
sed -i 's/爱派尔/ipair/g' phone_brand_device_model_translated.csv
sed -i 's/努比亚/nubia/g' phone_brand_device_model_translated.csv
sed -i 's/优米/youmi/g' phone_brand_device_model_translated.csv
sed -i 's/朵唯/dowe/g' phone_brand_device_model_translated.csv
sed -i 's/黑米/heymi/g' phone_brand_device_model_translated.csv
sed -i 's/锤子/hammer/g' phone_brand_device_model_translated.csv
sed -i 's/酷比魔方/koobee/g' phone_brand_device_model_translated.csv
sed -i 's/美图/meitu/g' phone_brand_device_model_translated.csv
sed -i 's/尼比鲁/nibilu/g' phone_brand_device_model_translated.csv
sed -i 's/一加/oneplus/g' phone_brand_device_model_translated.csv
sed -i 's/优购/yougo/g' phone_brand_device_model_translated.csv
sed -i 's/诺基亚/nokia/g' phone_brand_device_model_translated.csv
sed -i 's/糖葫芦/candy/g' phone_brand_device_model_translated.csv
sed -i 's/中国移动/ccmc/g' phone_brand_device_model_translated.csv
sed -i 's/语信/yuxin/g' phone_brand_device_model_translated.csv
sed -i 's/基伍/kiwu/g' phone_brand_device_model_translated.csv
sed -i 's/青橙/greeno/g' phone_brand_device_model_translated.csv
sed -i 's/华硕/asus/g' phone_brand_device_model_translated.csv
sed -i 's/夏新/panosonic/g' phone_brand_device_model_translated.csv
sed -i 's/维图/weitu/g' phone_brand_device_model_translated.csv
sed -i 's/艾优尼/aiyouni/g' phone_brand_device_model_translated.csv
sed -i 's/摩托罗拉/moto/g' phone_brand_device_model_translated.csv
sed -i 's/乡米/xiangmi/g' phone_brand_device_model_translated.csv
sed -i 's/米奇/micky/g' phone_brand_device_model_translated.csv
sed -i 's/大可乐/bigcola/g' phone_brand_device_model_translated.csv
sed -i 's/沃普丰/wpf/g' phone_brand_device_model_translated.csv
sed -i 's/神舟/hasse/g' phone_brand_device_model_translated.csv
sed -i 's/摩乐/mole/g' phone_brand_device_model_translated.csv
sed -i 's/飞秒/fs/g' phone_brand_device_model_translated.csv
sed -i 's/米歌/mige/g' phone_brand_device_model_translated.csv
sed -i 's/富可视/fks/g' phone_brand_device_model_translated.csv
sed -i 's/德赛/desci/g' phone_brand_device_model_translated.csv
sed -i 's/梦米/mengmi/g' phone_brand_device_model_translated.csv
sed -i 's/乐视/lshi/g' phone_brand_device_model_translated.csv
sed -i 's/小杨树/smallt/g' phone_brand_device_model_translated.csv
sed -i 's/纽曼/newman/g' phone_brand_device_model_translated.csv
sed -i 's/邦华/banghua/g' phone_brand_device_model_translated.csv
sed -i 's/E派/epai/g' phone_brand_device_model_translated.csv
sed -i 's/易派/epai/g' phone_brand_device_model_translated.csv
sed -i 's/普耐尔/pner/g' phone_brand_device_model_translated.csv
sed -i 's/欧新/ouxin/g' phone_brand_device_model_translated.csv
sed -i 's/西米/ximi/g' phone_brand_device_model_translated.csv
sed -i 's/海尔/haier/g' phone_brand_device_model_translated.csv
sed -i 's/波导/bodao/g' phone_brand_device_model_translated.csv
sed -i 's/糯米/nuomi/g' phone_brand_device_model_translated.csv
sed -i 's/唯米/weimi/g' phone_brand_device_model_translated.csv
sed -i 's/酷珀/kupo/g' phone_brand_device_model_translated.csv
sed -i 's/谷歌/google/g' phone_brand_device_model_translated.csv
sed -i 's/昂达/ada/g' phone_brand_device_model_translated.csv
sed -i 's/聆韵/lingyun/g' phone_brand_device_model_translated.csv
sed -i 's/小米/xiaomi/g' phone_brand_device_model_translated.csv
sed -i 's/华为/huawei/g' phone_brand_device_model_translated.csv
sed -i 's/魅族/meizu/g' phone_brand_device_model_translated.csv
sed -i 's/酷派/coolpad/g' phone_brand_device_model_translated.csv
sed -i 's/金立/gionee/g' phone_brand_device_model_translated.csv
sed -i 's/中兴/zte/g' phone_brand_device_model_translated.csv
sed -i 's/索尼/sony_china/g' phone_brand_device_model_translated.csv
sed -i 's/奇酷/qiku/g' phone_brand_device_model_translated.csv
sed -i 's/酷比/cube/g' phone_brand_device_model_translated.csv
sed -i 's/亿通/eton/g' phone_brand_device_model_translated.csv
sed -i 's/百立丰/lephone/g' phone_brand_device_model_translated.csv
sed -i 's/欧博信/opsson/g' phone_brand_device_model_translated.csv
sed -i 's/康佳/konka/g' phone_brand_device_model_translated.csv
sed -i 's/诺亚信/noain/g' phone_brand_device_model_translated.csv
